### ISSUE TITLE
quarto can open navbar items in new windows

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#13]
We had talked about this for the Initatives navbar, so that for example `NASA-Openscapes` linked to https://nasa-openscapes.github.io. Here's how to do it, Quarto >=1.3 required for this to work.

```
website:
  navbar:
    left:
      - text: "Home"
        file: index.qmd
        target: _blank
```
