### ISSUE TITLE
set up GitHub Actions so site will rebuild without need for local build

### ISSUE THREAD

**Issue by jules32** [Openscapes/website-new#41]
Once we're sure all the redirects and everything is working as we want it, let's get GA working

https://quarto.org/docs/publishing/netlify.html#github-action

**Comment by jules32** [comment]
This was the GitHub Action for the old events site (openscapes.github.io/events) - which I've just deleted

```
on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
```
