### ISSUE TITLE
Include author ORCID and citation in blog post yamls

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/website-new#49]
See Sam's post yaml

```
---
title: "Porting the Openscapes website from blogdown to Quarto"
description: |
  reflections of a first-time freelancer
author:
  - name: Samantha Csik
    url: https://samanthacsik.github.io/
    orcid: 0000-0002-5300-3075
date: 2023-08-03
citation: 
  url: https://samanthacsik.github.io/posts/2023-07-31-openscapes-website/
categories: [quarto, art, blog, coding, how-we-work]
image: openscapes_hex.png
# draft: true
---
```

**Looks like**

![Screenshot 2023-08-01 at 1 47 59 PM](https://github.com/Openscapes/website-new/assets/11927811/e8c31843-042c-49c7-b6ea-25e441a478b7)

![Screenshot 2023-08-01 at 1 48 50 PM](https://github.com/Openscapes/website-new/assets/11927811/99aab37e-5003-4190-b1c8-5f33353f21c7)
